apiDefinitions:
    main: nanonets_openapi.yaml
lint:
    extends:
        - recommended
    rules:
        no-unused-components: warning
referenceDocs:
    corsProxyUrl: "https://cors.redoc.ly"
    htmlTemplate: index.html
    theme:
        colors:
            primary:
                main: "#32329f"
